/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GameToken } from "./GameToken";

export { GameToken__factory } from "./factories/GameToken__factory";
